### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by dzuelke** [do3meli/monolog-cassandra#1]
Would be good, then one doesn't have to use `dev-master`.

**Comment by do3meli** [comment]
@dzuelke good idea. i have created [v0.1](https://github.com/do3meli/monolog-cassandra/releases/tag/v0.1)

**Comment by dzuelke** [comment]
Ah damn, sorry @do3meli, I wanted to comment but forgot... the `datastax/php-driver` dependency also needs a proper version selector; `dev-master` means the main `composer.json` needs to also require that version (or globally have a "dev" `minimum-stability` set, which is a very bad idea).

**Comment by do3meli** [comment]
good point, @dzuelke. do you have an up to date dev environment to test the current [DataStax PHP Driver v1.3.0](https://github.com/datastax/php-driver/releases/tag/v1.3.0) with it? i dont have one handy and the one i have installed in production is on a very old commit from [v1.0.1](https://github.com/datastax/php-driver/commit/1083e9c5de91c28f6d46959f127d145e4f65e292). i would be happy to accept any pull request.

**Comment by dzuelke** [comment]
Unfortunately I do not right now :(

**Comment by do3meli** [comment]
@dzuelke i have removed the minimum dev stability and set an according version for the DataStax PHP Driver. You now should be able to use v0.2 without having minimum-stability set to dev in your composer.json.

**Comment by dzuelke** [comment]
Thanks! I was just going to suggest that you simply set a version, since the current `dev-master` requirement means that anyone using the package must already be using the latest and greatest driver, so it's not really a concern :)
